module.exports = {
        name: 'insults',
        data: 'insults you ',
        format: 'prefixinsult',
        execute(message, args, bot) {
                const insults = ["your ao ugly santa goes ho ho holy shit",
                "your so ugly even scooby doo cant solve the mystery.",
                "your so ugly, bob the builder took one look at you and said we cant fix that.",
                "your so ygly when you look in the mirror your reflection runs away",
                "your such a disapointment that ted bundy said yeah nah, no thanks you can have that one back",
                "your so ugly when you were born the doctor slapped your parents",
                "you are the reason that your pearnts had a devoice",
                "your so ugly you mad ray charles flinch",
                "im told that two wrongs make a right clearly that didnt happend this time",
                "your so fat your on both sides of the family.",
                "your so poor you couldnt even spend the night",
                "your so stupid you studied for a drug test",
                "your so fat thanos had to snap twice.",
                "your so fat i took a picture of you last christmas and its still printing",
                "your so fat your baby photos had to be taken by a satalite",
                "your so fat you fall off both sides of the bed",
                "your so fat you dont need internet, your already world wide.",
                "your so ugly, when you walk into a bank they turn off the cameras.",
                "your so ugly that when you go to the dentis they make you lay face down.",
                "your so fat that you have to use a VCR as a beeper.",
                "your so fat that you got hit by a car and went to the hospital to have it removed.",
                "your so fat you were baptized at sea world.",
                "your so fat that when god said let their be light, he asked you to move out of the way.",
                "your so dumb it took you 2 hours to watch 60 minutes",
                "your so ugly, you threw a boomerang and it refused to come back",
                "your so ugly, your portraits hang themselves",
                "your so fat, your belly button gets home 15 mins before you do.",
                "your so dumb, you went to the dentist to get your blue tooth fixed.",
                "your so dumb you talk into an envelope to send voice mail.",
                "your so poor, ducks throw bread at you",
                "your so poor people only rob your house for practice",
                "your so dumb that you sold your car for gas money",
                "your so fat, you have to pay registration for both your ass cheeks.",
                "your like a civic verison of human, people only look at you cause your butt fucking ugly",
                "if i had a cent for everytime someone thought that you were funny i would be the poorest person around.",
                "you lost the game.",
                "your so stupid that they had to make a whole new word just for you. i dont even know what it is",
            ]

                const response = insults[Math.floor(Math.random() * insults.length)]
                message.channel.send(response)
        },
};